### ISSUE TITLE
Aufgabe 2: Ereignisbehandlung im Grafikeditor

### ISSUE THREAD

**Issue by thedodobird2** [john-francis96/M226#1]
_**Einleitung:**_
Der Grafikeditor ist im Moment eher ein „Grafikviewer“. Was fehlt ist die Interaktivität mit dem Benutzer. Das soll sich nun ändern. 
Sie haben sich in Aufgabe 1 über vier verschiedene Möglichkeiten informiert, wie Event-Handling in Java implementiert werden kann. Eine dieser Möglichkeiten sollen Sie nun in Ihr Grafikeditor-Programm integrieren.

**_Aufgabe:_**
- Sehen Sie sich den Screencast „Klassendiagramm Vorgabe.mp4“ an, damit Sie sich einen Überblick über die folgenden Aufträge verschaffen können.
- Integrieren Sie in Ihr bestehendes Grafikeditor-Programm die Klassen EditorFrame, EditorPanel, EditorControl und Grafikeditor. Sie finden diese im Ordner „Ressourcen“.
- Sie sollen Ihr Programm nun so ergänzen, dass die MousePressed und MouseReleased Ereignisse empfangen und bei der EditorControl-Klasse die passende Methoden aufgerufen wird. Überlegen Sie zuerst, welche der vier in den Screencasts beschriebenen Vorgehensweisen Sie umsetzen möchten, und integrieren Sie diese dann in Ihr Programm.
- Ergänzen Sie die Klasse EditorControl so, dass Rechtecke erzeugt werden können. Verwenden Sie die dazu vorbereitete Methode erzeugeFigurMitZweitemPunkt. Die erzeugten Rechtecke sollen in die Zeichnung hinzugefügt werden. Sollten Sie in der Klasse Zeichnung bisher einen Array verwendet haben, ersetzen Sie diesen durch eine Liste. Weitere Informationen zu Listen finden Sie in der Präsentation „Ereignisse und Listen.ppt“ oder im Buch im Kapitel 5.4.1.
- Implementieren Sie die Methode allesNeuZeichnen in der Klasse EditorControl, damit die Figuren gezeichnet werden. Damit das Zeichnen funktioniert, müssen Sie die repaint()-Methode des Panels aufrufen. Überlegen Sie in welchem Moment die Methode ausgeführt werden muss. Schauen Sie dazu noch einmal den Screencast zu den Vorgaben an oder orientieren Sie sich mit Hilfe des Buches (Kapitel 10.3).

**Comment by john-francis96** [comment]
Müssen wir K3.3 am Donnerstag abgeben?

**Comment by thedodobird2** [comment]
@john-francis96 ja, K3.3 und K3.4, dafür benötigen wir aber eventuell noch die zusätzlichen Kompetenzen von AB3-5 (1.5 & 3.5)

**Comment by john-francis96** [comment]
ök

**Comment by thedodobird2** [comment]
K3.3 abgegeben!
