### ISSUE TITLE
Aufgabe 2: Fachklassen und technische Klassen in einem SW-Design unterscheiden

### ISSUE THREAD

**Issue by thedodobird2** [john-francis96/M226#6]
**_Einleitung:_**
Am Anfang der Entwicklung einer neuen Software stehen die Benutzerbedürfnisse im Vordergrund. Hierbei muss der Informatiker sich ein genaues Bild machen, welche Abläufe oder Aufgaben umgesetzt werden müssen. Diese Analyse führt zu einem Teil der Klassen des zu erstellenden Software-Designs:
- Fachliche Klassen: werden benötigt zur Abbildung des Anwendungsbereiches 
Als nächster Schritt muss sich mit der (informatik-) technischen Umsetzung der festgelegten fachlichen Anforderungen auseinandergesetzt werden. Die daraus resultierenden Klassen des Entwurfs sind:
- Technische Klassen: werden eingesetzt, um die fachlichen Anforderungen mit den technischen Möglichkeiten umzusetzen.

**_Aufgabe:_**
Das folgende Klassendiagramm bildet einen Teil eines Spiels ab. Es handelt sich um das Spiel „Snake“. Das Spiel funktioniert wie folgt: Zu Beginn werden eine Anzahl von Diamanten und eine Schlange auf dem Spielfeld verteilt. Die Schlange kann mit der Tastatur gesteuert werden (auf/ab/links/rechts). Das Spiel ist gewonnen, wenn die Schlange alle Diamanten gefressen hat, ohne mit der Spielgrenze oder mit sich selbst zu kollidieren. Die Schlange wächst mit jedem gefressenen Diamanten ein Stück.
- Teilen Sie die Klassen des Snake-Spieles im nachfolgenden Klassendiagramm in fachliche oder technische Klassen ein.

![k1 3pic](https://cloud.githubusercontent.com/assets/10851587/15240829/8578a6aa-18ec-11e6-8b95-f6998e6c5510.png)

**Comment by john-francis96** [comment]
done and dusted!
