### ISSUE TITLE
Vertiefungs- und Ergänzungsaufgaben

### ISSUE THREAD

**Issue by thedodobird2** [john-francis96/M226#7]
**_Einleitung_**
Die folgenden Aufgaben dienen Ihrer individuellen Vertiefung. Sie können diese nach Belieben bearbeiten und dadurch auch Zusatzkompetenzen erlangen. Die Aufgaben sind bewusst offen formuliert und Sie werden für die Lösung im Web recherchieren müssen.

**_Weitere Elemente im UML-Klassendiagramm_**
Zeichnen Sie ein Klassendiagramm von Ihrem Grafikeditorprogramm mit den dort enthaltenen zusätzlichen Elementen wie Paketen, Interfaces, etc.

**Comment by john-francis96** [comment]
Lè Fertig
